### ISSUE TITLE
Firmware doesn't suite for device

### ISSUE THREAD

**Issue by Hotix71** [ClockSelect/myevic#81] opened 2016-10-15 19:53 UTC
Hello,

since the release f92ddb0 the firmware can not be updated to any of my VTC's.

All other firmwares original or 3rd party work without any problem, only myevic releases from today do not and it doesn't matter if i use the flash tool coming from Joyetech or the NFE updater. So i strongly believe it's an issue with the firmware binaries.

As said: All other firmware from myevic, any other firmware or the original ones can be updated without any issue!

Thank you!

**Comment by ClockSelect** [comment] 2016-10-15 20:44
Hello
Just fixed. Duplicate of #80.

**Closed as completed** 2016-10-16 04:09 UTC
Labels: duplicate
