### ISSUE TITLE
Please add power bank mode like rs300x!

### ISSUE THREAD

**Issue by userdsp** [ClockSelect/myevic#257] opened 2017-01-26 19:37 UTC
Please add power bank mode like rs300x!

**Comment by lostvoid** [comment] 2017-01-30 01:00
I second this. The USB charging is a major selling point for the rx300.

**Comment by ClockSelect** [comment] 2017-01-30 19:25
Duplicate of #237 
Thinking about it

**Comment by ClockSelect** [comment] 2017-01-30 19:26
(Closed due to duplicated - continue discussion in #237)

**Closed as completed by ClockSelect** 2017-01-30 19:26 UTC
Labels: duplicate
