### ISSUE TITLE
During LSL The Charging display its not available

### ISSUE THREAD

**Issue by afol2** [ClockSelect/myevic#92] opened 2016-10-20 21:39 UTC
First of all, thank for your support, i think this is a astonishing effort you have in this Firmware, big fan of you by the way.

I have found that during LSL its "ON" on my EVIC VTC Mini, after you plugged the USB cable to charge the device, the screen that tell you Batt Volt, Temp and % of the battery its not shown. I'm guessing its because the device do not recognize it is light sleep mode, isn't there a way it could be done ?

**Comment by ClockSelect** [comment] 2016-10-21 00:36
Light or Deep Sleep do not make any difference.
It depends on the Screen Saver and/or Stealth Mode settings.
If you configure a Screen Saver, the box will enter sleep mode after the duration of the screen saver. If you activate Stealth Mode, it won't be shown either.

Also see #85 on this topic.

**Comment by ClockSelect** [comment] 2016-10-21 00:54
BTW: This does not prevent the box from charging. Cells will be charged normally wathever the display (at least single-cell boxes).

**Comment by ClockSelect** [comment] 2016-10-21 06:35
I modified things, so that behavior should be more intuitive.

**Comment by ClockSelect** [comment] 2016-10-22 22:10
This issue is more or less a duplicate of #85

**Closed as completed** 2016-10-23 06:58 UTC
Labels: duplicate, enhancement, question
