### ISSUE TITLE
Suggestion 12/24hr clock option

### ISSUE THREAD

**Issue by jsmith70** [ClockSelect/myevic#223] opened 2016-12-23 11:03 UTC
Would it be possible to implement an option to switch between 12hr and 24hr clock formats? I know reading 24hr time isn't that much more of a hassle, but I'm much more accustomed to 12hr time so it would be nice.

**Box Model: eVic VTC Mini**

**Comment by ClockSelect** [comment] 2016-12-30 02:43
Duplicate of #151

**Closed as completed** 2017-01-13 03:40 UTC
Labels: duplicate, wontdo
